<?php

/**
 * This is the model base class for the table "yii_forum".
 * DO NOT MODIFY THIS FILE! It is automatically generated by giix.
 * If any changes are necessary, you must set or override the required
 * property or method in class "Forum".
 *
 * Columns in table "yii_forum" available as properties of the model,
 * and there are no model relations.
 *
 * @property integer $forum_id
 * @property string $name
 * @property string $description
 * @property string $type
 * @property integer $parentforum
 * @property string $last_poster_name
 * @property integer $last_poster_id
 * @property string $last_thread
 * @property integer $last_post_id
 * @property integer $last_post_time
 *
 */
abstract class BaseForum extends GxActiveRecord {

	public static function model($className=__CLASS__) {
		return parent::model($className);
	}

	public function tableName() {
		return 'yii_forum';
	}

	public static function label($n = 1) {
		return Yii::t('app', 'Forum', $n);
	}

	public static function representingColumn() {
		return 'name';
	}

	public function rules() {
		return array(
			array('name, description, type, last_poster_name, last_poster_id, last_thread, last_post_id, last_post_time', 'required'),
			array('parentforum, last_poster_id, last_post_id, last_post_time', 'numerical', 'integerOnly'=>true),
			array('name, last_poster_name, last_thread', 'length', 'max'=>120),
			array('type', 'length', 'max'=>1),
			array('parentforum', 'default', 'setOnEmpty' => true, 'value' => null),
			array('forum_id, name, description, type, parentforum, last_poster_name, last_poster_id, last_thread, last_post_id, last_post_time', 'safe', 'on'=>'search'),
		);
	}

	public function relations() {
		return array(
		);
	}

	public function pivotModels() {
		return array(
		);
	}

	public function attributeLabels() {
		return array(
			'forum_id' => Yii::t('app', 'Forum'),
			'name' => Yii::t('app', 'Name'),
			'description' => Yii::t('app', 'Description'),
			'type' => Yii::t('app', 'Type'),
			'parentforum' => Yii::t('app', 'Parentforum'),
			'last_poster_name' => Yii::t('app', 'Last Poster Name'),
			'last_poster_id' => Yii::t('app', 'Last Poster'),
			'last_thread' => Yii::t('app', 'Last Thread'),
			'last_post_id' => Yii::t('app', 'Last Post'),
			'last_post_time' => Yii::t('app', 'Last Post Time'),
		);
	}

	public function search() {
		$criteria = new CDbCriteria;

		$criteria->compare('forum_id', $this->forum_id);
		$criteria->compare('name', $this->name, true);
		$criteria->compare('description', $this->description, true);
		$criteria->compare('type', $this->type, true);
		$criteria->compare('parentforum', $this->parentforum);
		$criteria->compare('last_poster_name', $this->last_poster_name, true);
		$criteria->compare('last_poster_id', $this->last_poster_id);
		$criteria->compare('last_thread', $this->last_thread, true);
		$criteria->compare('last_post_id', $this->last_post_id);
		$criteria->compare('last_post_time', $this->last_post_time);

		return new CActiveDataProvider($this, array(
			'criteria' => $criteria,
		));
	}
}